export const platformOptions = ['All Platforms', 'PC (Windows)', 'Web Browser']

export const genreOptions =  [
  'All Genres',
  'MMORPG',
  'Shooter',
  'Strategy',
  'MOBA',
  'Racing',
  'Sports',
  'Social',
  'Sandbox',
  'Open World',
  'Survival',
  'PVP',
  'PVE',
  'Pixel',
  'Voxel',
  'Zombie',
  'Turn Based',
  'First Person',
  'Third Person',
  'Top-Down',
  'Tank',
  'Space',
  'Sailing',
  'Side-Scroller',
  'Superhero',
  'Permadeath',
  'Card',
  'Battle Royale',
  'MMO',
  'MMOFPS',
  'MMOTPS',
  '3D',
  '2D',
  'Anime',
  'Fantasy',
  'Sci-Fi',
  'Fighting',
  'Action RPG',
  'Action',
  'Military',
  'Martial Arts',
  'Flight',
  'Low-Spec',
  'Tower Defense',
  'Horror',
  'MMORTS'
]

export const sortOptions = [
  'Relevance',
  'Popularity',
  'Release Date',
  'Alphabetical'
]